Repository ansible/tox-ansible, pull requests merged in 2020-10, with the labels that each got.

#26 Streamline scenario detection
  README.md
  src/tox_ansible/ansible/__init__.py
Labels: bug

#28 Adopt setuptools packaging
  .gitignore
  pyproject.toml
  setup.cfg
  setup.py
Labels: feature

#29 Add Python 3.9
  .github/workflows/tox.yml
  tox.ini
Labels: test

#31 Add support for more driver types
  src/tox_ansible/tox_test_case.py
  tests/test_tox_test_case.py
Labels: enhancement

#30 Change license to MIT from GPLv3
  LICENSE
  setup.cfg
Labels: enhancement

#33 Fix lint case
  src/tox_ansible/tox_helper.py
  src/tox_ansible/tox_lint_case.py
  tests/test_tox_lint_case.py
Labels: bug
