Repository ansible/tox-ansible, pull requests merged in 2020-08, with the labels that each got.

#6 Add black styling
  .pre-commit-config.yaml
  setup.py
  src/tox_ansible/ansible/__init__.py
  src/tox_ansible/ansible/collection.py
  src/tox_ansible/ansible/role.py
  src/tox_ansible/ansible/scenario.py
  src/tox_ansible/compat.py
  src/tox_ansible/filter/__init__.py
  src/tox_ansible/filter/base_filter.py
  src/tox_ansible/filter/by_driver.py
  src/tox_ansible/filter/by_role.py
  src/tox_ansible/filter/by_scenario.py
  src/tox_ansible/hooks.py
  src/tox_ansible/matrix/__init__.py
  src/tox_ansible/matrix/axes.py
  src/tox_ansible/options.py
  src/tox_ansible/tox_base_case.py
  src/tox_ansible/tox_helper.py
  src/tox_ansible/tox_lint_case.py
  src/tox_ansible/tox_test_case.py
  tests/test_ansible.py
  tests/test_by_driver.py
  tests/test_by_role.py
  tests/test_by_scenario.py
  tests/test_everything.py
  tests/test_filter.py
  tests/test_matrix.py
  tests/test_options.py
  tests/test_role.py
  tests/test_scenario.py
  tests/test_tox_lint_case.py
  tests/test_tox_test_case.py
  tests/util.py
  tox.ini
Labels: skip-changelog

#7 Fix pypi releases
  .github/workflows/pushes.yml
Labels: skip-changelog

#9 Added config for labels and release-drafter
  .github/labels.yml
  .github/release-drafter.yml
Labels: skip-changelog

#10 Add more linters
  .pre-commit-config.yaml
  .yamllint
  pyproject.toml
  setup.py
  src/tox_ansible/ansible/__init__.py
  src/tox_ansible/ansible/collection.py
  src/tox_ansible/ansible/role.py
  src/tox_ansible/ansible/scenario.py
  src/tox_ansible/filter/__init__.py
  src/tox_ansible/hooks.py
  src/tox_ansible/options.py
  src/tox_ansible/tox_helper.py
  src/tox_ansible/tox_lint_case.py
  src/tox_ansible/tox_test_case.py
  tests/test_by_driver.py
  tests/test_by_role.py
  tests/test_by_scenario.py
  tests/test_collection.py
  tests/test_everything.py
  tests/test_filter.py
  tests/test_matrix.py
  tests/test_options.py
  tests/test_scenario.py
  tests/test_tox_helper.py
  tests/test_tox_lint_case.py
  tests/test_tox_test_case.py
Labels: skip-changelog

#4 Sort output and add descriptions
  setup.py
  src/tox_ansible/hooks.py
  src/tox_ansible/tox_helper.py
  src/tox_ansible/tox_lint_case.py
  src/tox_ansible/tox_test_case.py
  tox.ini
Labels: enhancement

#15 Drop Python < 3.6
  .github/workflows/pushes.yml
  setup.py
  tests/fixtures/collection/tox.ini
  tests/fixtures/expand_collection/tox.ini
  tests/test_everything.py
  tests/test_filter.py
  tox.ini
Labels: major
