Repository ansible/tox-ansible, pull requests merged in 2021-09, with the labels that each got.

#87 Make it possible to disable plugin activation
  src/tox_ansible/hooks.py
  src/tox_ansible/options.py
  tests/fixtures/expand_collection/tox.ini
  tests/fixtures/expand_collection_comma/tox.ini
  tests/fixtures/expand_collection_newlines/tox.ini
  tests/fixtures/has_deps/tox.ini
  tests/fixtures/not_collection/tox.ini
  tests/fixtures/nothing/molecule/dont_find_me/molecule.yml
  tests/fixtures/nothing/tox.ini
  tests/fixtures/simplified/tox.ini
  tests/test_ansible.py
  tests/test_everything.py
  tests/test_options.py
Labels: major

#107 Add missing SSH_AUTH_SOCK to implicit passenv
  src/tox_ansible/tox_helper.py
Labels: bug

#108 Create CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog
