Repository ansible/tox-ansible, pull requests merged in 2024-02, with the labels that each got.

#264 Unify requirements files
  .config/constraints.txt
  .config/requirements-dev.in
  .config/requirements-docs.in
  .config/requirements-docs.txt
  .config/requirements-test.in
  .github/dependabot.yml
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
  tests/integration/test_user_provided.py
  tox.ini
Labels: skip-changelog

#269 Update dependencies to include new mkdocs-ansible branding
  .config/constraints.txt
  .gitignore
  mkdocs.yml
Labels: skip-changelog, dependencies

#270 Update readme to include calver release information
  .config/dictionary.txt
  README.md
Labels: documentation, enhancement
