Repository ansible/tox-ansible, pull requests merged in 2024-06, with the labels that each got.

#313 Add 2.17 support
  src/tox_ansible/plugin.py
Labels: enhancement

#315 chore: Update tox.ini
  tox.ini
Labels: skip-changelog

#317 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#318 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#320 chore: Update .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: skip-changelog

#324 chore: Update .github/workflows/tox.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#326 Revert code type changes
  .config/constraints.txt
  .config/requirements.in
  .pre-commit-config.yaml
  src/tox_ansible/plugin.py
  tests/unit/test_type.py
Labels: bug

#325 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#327 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#328 Add known first party
  pyproject.toml
  tests/conftest.py
Labels: skip-changelog

#330 chore: Update .vscode/settings.json
  .vscode/settings.json
Labels: skip-changelog

#331 chore: Update tox.ini
  tox.ini
Labels: skip-changelog

#332 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#333 Add pip upgrade
  pyproject.toml
  src/tox_ansible/plugin.py
  tests/unit/test_plugin.py
Labels: bug

#334 Revert pip upgrade
  pyproject.toml
  src/tox_ansible/plugin.py
  tests/unit/test_plugin.py
Labels: bug

#336 Exclude *-py3.10-devel from matrix
  src/tox_ansible/plugin.py
  tests/conftest.py
  tests/unit/test_type.py
Labels: bug

#340 Correct exclude
  .pre-commit-config.yaml
Labels: skip-changelog

#342 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog
