Repository ansible/tox-ansible, pull requests merged in 2024-11, with the labels that each got.

#389 Start using uv
  .config/constraints.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#388 Add support for py313 and ansible 2.18
  .github/workflows/tox.yml
  pyproject.toml
  src/tox_ansible/plugin.py
  tests/conftest.py
  tests/unit/test_type.py
Labels: enhancement

#391 Replace cp --parents with bash script for macOS compatibility
  src/tox_ansible/plugin.py
Labels: bug

#394 Remove self type
  .pre-commit-config.yaml
  pyproject.toml
  src/tox_ansible/plugin.py
Labels: skip-changelog
