Repository ansible/tox-ansible, pull requests merged in 2025-05, with the labels that each got.

#442 Disable mkdocs-material social plugin
  mkdocs.yml
Labels: skip-changelog

#439 Add merge_group handler for tox workflow
  .github/workflows/tox.yml
Labels: bug, github_actions

#448 Remove support for ansible-core 2.16 due to EOL
  src/tox_ansible/plugin.py
  tests/conftest.py
  tests/unit/test_type.py
Labels: minor

#446 Update dependencies
  .config/constraints.txt
Labels: skip-changelog
